/**
 * ====================================================
 *  BRAIN NETWORK EXPORT - REAL FILE OUTPUT
 * ====================================================
 *  Export generated pages and projects as real files
 * ====================================================
 */

import { NextResponse } from 'next/server';
import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';
import { existsSync } from 'fs';

// Output directory for exported projects
const OUTPUT_DIR = join(process.cwd(), 'public', 'exports');

export async function POST(request) {
  try {
    const body = await request.json();
    const { action, data } = body;

    switch (action) {
      case 'export-landing':
        return await exportLandingPage(data);

      case 'export-project':
        return await exportProject(data);

      case 'export-zip':
        return await exportAsZip(data);

      default:
        return NextResponse.json({
          success: false,
          error: 'Unknown action'
        }, { status: 400 });
    }
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({
      success: false,
      error: error.message
    }, { status: 500 });
  }
}

async function exportLandingPage(data) {
  const { html, companyName, industry = 'default' } = data;

  // Create output directory
  const projectId = `landing-${Date.now()}`;
  const projectDir = join(OUTPUT_DIR, projectId);

  if (!existsSync(OUTPUT_DIR)) {
    await mkdir(OUTPUT_DIR, { recursive: true });
  }
  await mkdir(projectDir, { recursive: true });

  // Write HTML file
  const htmlPath = join(projectDir, 'index.html');
  await writeFile(htmlPath, html, 'utf-8');

  // Generate package.json for the project
  const packageJson = {
    name: companyName.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    description: `Landing page generated by Brain Network`,
    scripts: {
      start: 'npx serve .',
      dev: 'npx live-server'
    },
    keywords: ['landing-page', 'brain-network', industry],
    generated: new Date().toISOString()
  };

  await writeFile(
    join(projectDir, 'package.json'),
    JSON.stringify(packageJson, null, 2),
    'utf-8'
  );

  // Generate README
  const readme = `# ${companyName} Landing Page

Generated by **Brain Network** - The 1000-brain neural supercomputer

## Quick Start

\`\`\`bash
npm start
\`\`\`

Or simply open \`index.html\` in your browser.

## Files

- \`index.html\` - Main landing page
- \`package.json\` - Project configuration

## Customization

Edit the HTML file to customize content, colors, and styling.

---

*Generated on ${new Date().toLocaleString()}*
`;

  await writeFile(join(projectDir, 'README.md'), readme, 'utf-8');

  // Return public URL
  const publicUrl = `/exports/${projectId}`;

  return NextResponse.json({
    success: true,
    data: {
      projectId,
      url: publicUrl,
      indexUrl: `${publicUrl}/index.html`,
      files: ['index.html', 'package.json', 'README.md'],
      exportedAt: Date.now()
    }
  });
}

async function exportProject(data) {
  const { project, format = 'nextjs' } = data;

  const projectId = `project-${Date.now()}`;
  const projectDir = join(OUTPUT_DIR, projectId);

  if (!existsSync(OUTPUT_DIR)) {
    await mkdir(OUTPUT_DIR, { recursive: true });
  }
  await mkdir(projectDir, { recursive: true });

  // Structure based on format
  if (format === 'nextjs') {
    // Create Next.js project structure
    await mkdir(join(projectDir, 'src', 'app'), { recursive: true });
    await mkdir(join(projectDir, 'src', 'components'), { recursive: true });
    await mkdir(join(projectDir, 'public'), { recursive: true });

    // Package.json
    const packageJson = {
      name: project.name || 'brain-network-project',
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint'
      },
      dependencies: {
        next: '^14.0.0',
        react: '^18.2.0',
        'react-dom': '^18.2.0'
      },
      devDependencies: {
        '@types/node': '^20.0.0',
        '@types/react': '^18.2.0',
        typescript: '^5.0.0',
        tailwindcss: '^3.3.0'
      }
    };

    await writeFile(
      join(projectDir, 'package.json'),
      JSON.stringify(packageJson, null, 2),
      'utf-8'
    );

    // Basic page
    const pageContent = `export default function Home() {
  return (
    <main className="min-h-screen flex items-center justify-center bg-black text-white">
      <div className="text-center">
        <h1 className="text-5xl font-bold mb-4">
          ${project.name || 'Your Project'}
        </h1>
        <p className="text-xl opacity-70">
          Generated by Brain Network
        </p>
      </div>
    </main>
  );
}
`;

    await writeFile(
      join(projectDir, 'src', 'app', 'page.tsx'),
      pageContent,
      'utf-8'
    );

    // Layout
    const layoutContent = `import './globals.css';

export const metadata = {
  title: '${project.name || 'Brain Network Project'}',
  description: 'Generated by Brain Network',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

    await writeFile(
      join(projectDir, 'src', 'app', 'layout.tsx'),
      layoutContent,
      'utf-8'
    );

    // Global CSS
    const globalCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 255, 255, 255;
  --background-rgb: 10, 10, 18;
}

body {
  color: rgb(var(--foreground-rgb));
  background: rgb(var(--background-rgb));
}
`;

    await writeFile(
      join(projectDir, 'src', 'app', 'globals.css'),
      globalCss,
      'utf-8'
    );

    // Tailwind config
    const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: { extend: {} },
  plugins: [],
};
`;

    await writeFile(
      join(projectDir, 'tailwind.config.js'),
      tailwindConfig,
      'utf-8'
    );
  }

  return NextResponse.json({
    success: true,
    data: {
      projectId,
      url: `/exports/${projectId}`,
      format,
      exportedAt: Date.now()
    }
  });
}

async function exportAsZip(data) {
  // Would use archiver or similar to create ZIP
  // For now, return the directory structure
  return NextResponse.json({
    success: true,
    data: {
      message: 'ZIP export coming soon',
      projectId: data.projectId
    }
  });
}

// List exports
export async function GET() {
  try {
    const { readdir } = await import('fs/promises');

    if (!existsSync(OUTPUT_DIR)) {
      return NextResponse.json({
        success: true,
        data: { exports: [] }
      });
    }

    const exports = await readdir(OUTPUT_DIR);

    return NextResponse.json({
      success: true,
      data: {
        exports: exports.map(name => ({
          id: name,
          url: `/exports/${name}`,
          indexUrl: `/exports/${name}/index.html`
        }))
      }
    });
  } catch (error) {
    return NextResponse.json({
      success: false,
      error: error.message
    }, { status: 500 });
  }
}
