[build]
  publish = "."
  command = "echo 'ORBOS Deploy'"

[[redirects]]
  from = "/api/*"
  to = "/0r8-starter/api/:splat"
  status = 200

[[redirects]]
  from = "/terminal"
  to = "/0r8-starter/public/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-ORBOS-Version = "1.0.0"
    X-Powered-By = "ORBOS/eKo"

[context.production.environment]
  ORBOS_MODE = "production"
  NODE_ENV = "production"
